services:
  - type: web
    name: profilebackend
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_TELEGRAM_ID
        sync: false
      - key: MONGO_URI
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: SELF_URL
        value: https://profilebackend-5mwr.onrender.com
      - key: NODE_ENV
        value: production
